criterion:
  ent_weight: 0.0
  final_sharpen: 0.25
  me_max: true
  memax_weight: 1.0
  num_proto: 1024
  start_sharpen: 0.25
  temperature: 0.1
  batch_size: 64
  use_ent: true
  use_sinkhorn: true
data:
  color_jitter_strength: 0.5
  pin_mem: true
  num_workers: 10
  image_folder: iwildcam_v2.0/
  label_smoothing: 0.0
  patch_drop: 0.15
  rand_size: 224
  focal_size: 96
  rand_views: 1
  focal_views: 10
  root_path: /srv/datasets/wilds/data/
logging:
  folder: pretrained/msn_pt/
  write_tag: vits16_in1k_iwc_lr_1e-5
  tensorboard_dir: logs/tboard/
meta:
  bottleneck: 1
  copy_data: false
  drop_path_rate: 0.0
  hidden_dim: 2048
  load_checkpoint: false
  model_name: deit_small
  output_dim: 256
  read_checkpoint: null
  use_bn: true
  use_fp16: false
  use_pred_head: false
  load_encoder: true
  encoder_path: pretrained/msn/vits16_800ep.pth.tar
optimization:
  clip_grad: 3.0
  epochs: 400
  final_lr: 1.0e-08
  final_weight_decay: 0.4
  lr: 1.0e-05
  start_lr: 2.0e-06
  warmup: 15
  weight_decay: 0.04
