meta:
  model_name: deit_small
  master_port: 8888
  load_checkpoint: false
  training: true
  finetuning: false
  eval_type: bslplpl
  device: cuda:0
data:
  root_path_train: /srv/share4/datasets/wilds/data/
  image_folder_train: iwildcam_v2.0/
  subset_file: subsets/iwildcam_subsets1/1percent.txt
  root_path_test: /srv/share4/datasets/wilds/data/
  image_folder_test: iwildcam_v2.0/
  num_classes: 182
  val_split: id_val
optimization:
  weight_decay: 0.001
  lr: 0.01
  epochs: 100
  batch_size: 16
  num_blocks: 1
  normalize: true
  nesterov: false
  dampening: 0.9
logging:
  folder: pretrained/msn/
  tboard_folder: logs/tboard/
  write_tag: msn_vits16_iwc_bslplpl_1percent
  pretrain_path: vits16_800ep.pth.tar