meta:
  model_name: clip_vitb16
  master_port: 8888
  load_checkpoint: false
  training: true
  finetuning: false
  eval_type: lineval
  device: cuda:0
data:
  root_path_train: /srv/share4/datasets/ImageNet/
  image_folder_train: imagenet/
  subset_file: subsets/imagenet_subsets1/1imgs_class.txt
  root_path_test: /srv/share4/datasets/ImageNet/
  image_folder_test: imagenet/
  num_classes: 1000
  val_split: null
optimization:  
  lr: 6.4
  epochs: 100
  batch_size: 128
  num_blocks: 1
  normalize: true
  weight_decay: 0.0
  nesterov: true
  dampening: 0.0
logging:
  folder: pretrained/clip/
  tboard_folder: logs/tboard/
  write_tag: clip_vitb16_inet_lineval_1imgs_class
  pretrain_path: ViTB16.pth