meta:
  model_name: deit_small
  master_port: 8888
  load_checkpoint: false
  training: true
  finetuning: true
  eval_type: lineval
  device: cuda:0
data:
  root_path_train: ../datasets/wilds/data/
  image_folder_train: camelyon17_v1.0/
  subset_file: null
  root_path_test: ../datasets/wilds/data/
  image_folder_test: camelyon17_v1.0/
  num_classes: 2
  val_split: id_val
optimization:
  weight_decay: 0.01
  lr: 0.0001
  epochs: 10
  batch_size: 32
  num_blocks: 1
  normalize: false
  nesterov: false
  dampening: 0.0
logging:
  folder: pretrained/dino/
  tboard_folder: logs/tboard/
  write_tag: dino_vits16_cmlyn_ft_full
  pretrain_path: dino_deitsmall16_pretrain.pth