meta:
  model_name: deit_base
  master_port: 8888
  load_checkpoint: false
  training: true
  finetuning: false
  eval_type: lineval
  device: cuda:0
data:
  root_path_train: ../datasets/wilds/data/
  image_folder_train: camelyon17_v1.0/
  subset_file: subsets/camelyon17_subsets1/15000imgs_class.txt
  root_path_test: ../datasets/wilds/data/
  image_folder_test: camelyon17_v1.0/
  num_classes: 2
  val_split: id_val
optimization:
  weight_decay: 0.001
  lr: 0.001
  epochs: 20
  batch_size: 32
  num_blocks: 1
  normalize: false
  nesterov: false
  dampening: 0.0
logging:
  folder: pretrained/msn/
  tboard_folder: logs/tboard/
  write_tag: msn_vitb16_cmlyn_lp_15000imgs_class
  pretrain_path: vitb16_600ep.pth.tar